# Generated by Django 2.1.3 on 2018-12-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('formal_sort_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year_published', models.IntegerField()),
                ('amazon_asin', models.CharField(max_length=100)),
                ('is_fiction', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('author', models.ManyToManyField(to='books.Author')),
            ],
        ),
    ]
