# Generated by Django 2.1.3 on 2018-12-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181204_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['formal_sort_name']},
        ),
    ]
