# Generated by Django 3.2.5 on 2021-07-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
