# Generated by Django 3.2.5 on 2021-07-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_training_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
