# Generated by Django 2.1.3 on 2018-12-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=300)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uspto_number', models.IntegerField()),
                ('title', models.TextField()),
                ('inventors', models.TextField()),
                ('assignee', models.TextField()),
                ('abstract', models.TextField()),
                ('date_filed', models.DateField()),
                ('date_granted', models.DateField()),
                ('continuation_of_uspto_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('qualifications', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SkillArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.SkillArea'),
        ),
    ]
