# Generated by Django 2.1.3 on 2018-12-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_ended',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
