# Generated by Django 2.1.3 on 2018-12-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20181230_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
