# Generated by Django 2.1.3 on 2018-12-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20181230_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='continuation_of_uspto_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
