# Generated by Django 2.1.3 on 2018-12-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year_released', models.IntegerField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('imdb_id', models.CharField(max_length=50)),
                ('date_watched', models.DateField()),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
